spring:
  application:
    name: BOOK_BE
  datasource:
    url: jdbc:mysql://localhost:3306/HBD?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  jackson:
    serialization:
      fail-on-empty-beans: false

  sql:
    init:
      mode: always

server:
  tomcat:
    threads:
      max: 200                
      min-spare: 10          

# Springdoc OpenAPI Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs