spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/book
    username: postgres
    password: ins123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    defer-datasource-initialization: true

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:db/data.sql
